# Generated by Django 4.2.16 on 2025-04-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_postfeatures_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfeatures',
            options={'managed': False},
        ),
    ]
