# Generated by Django 4.2.16 on 2025-04-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KATAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfeatures',
            options={'managed': True},
        ),
    ]
